language: python
python: 2.7
env:
  - TOX_ENV=py33-master
  - TOX_ENV=py33-1.7.x
  - TOX_ENV=py33-1.6.x
  - TOX_ENV=py33-1.5.x
  - TOX_ENV=py34-master
  - TOX_ENV=py34-1.7.x
  - TOX_ENV=py34-1.6.x
  - TOX_ENV=py34-1.5.x
  - TOX_ENV=pypy-master
  - TOX_ENV=pypy-1.7.x
  - TOX_ENV=pypy-1.6.x
  - TOX_ENV=pypy-1.5.x
  - TOX_ENV=py27-master
  - TOX_ENV=py27-1.7.x
  - TOX_ENV=py27-1.6.x
  - TOX_ENV=py27-1.5.x
  - TOX_ENV=py26-1.5.x
install:
  - pip install tox
script:
  - tox -e $TOX_ENV

