language: python
python: 3.5
sudo: false
env:
  - TOX_ENV=docs
  - TOX_ENV=lint
  - TOX_ENV=py27-django18
  - TOX_ENV=py27-django19
  - TOX_ENV=py27-django110
  - TOX_ENV=py27-django111
  - TOX_ENV=py34-django18
  - TOX_ENV=py34-django19
  - TOX_ENV=py34-django110
  - TOX_ENV=py34-django111
  - TOX_ENV=py34-django20
  - TOX_ENV=py35-django18
  - TOX_ENV=py35-django19
  - TOX_ENV=py35-django110
  - TOX_ENV=py35-django111
  - TOX_ENV=py35-django20
  - TOX_ENV=py35-djangomaster
matrix:
  include:
    - env: TOX_ENV=py36-django18
      python: "3.6"
    - env: TOX_ENV=py36-django19
      python: "3.6"
    - env: TOX_ENV=py36-django110
      python: "3.6"
    - env: TOX_ENV=py36-django111
      python: "3.6"
    - env: TOX_ENV=py36-django20
      python: "3.6"
    - env: TOX_ENV=py36-djangomaster
      python: "3.6"
install: pip install tox
script: tox -e $TOX_ENV
cache: pip
