language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "pypy"
env:
  - DJANGO_VERSION=master
  - DJANGO_VERSION=1.7.x
  - DJANGO_VERSION=1.6.x
  - DJANGO_VERSION=1.5.x
install:
  - pip install tox
script:
  - tox -e "$TRAVIS_PYTHON_VERSION-$DJANGO_VERSION"
matrix:
  exclude:
   - python: "2.6"
     env: DJANGO_VERSION=master
   - python: "2.6"
     env: DJANGO_VERSION=1.7.x
